version: "3.9"

networks:
  titiler_stable:
    name: titiler_stable
    driver: overlay
    attachable: true

services:
  titiler_stable:
    image: developmentseed/titiler:$DOCKER_IMAGE_LABEL
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.apps == true
      rollback_config:
        parallelism: 0
      update_config:
        parallelism: 0
        order: stop-first
        failure_action: rollback
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          cpus: "1"
          memory: 1G
    environment:
      - PORT=8000
      - WORKERS_PER_CORE=1
    ports:
      - 7003:8000
    networks:
      - titiler_stable